# Auto-Sprint Orchestrator Workflow
name: auto-sprint
description: "Autonomous sprint loop that cycles through create-story → dev-story → code-review until sprint scope is complete. Spawns sub-agents for each phase to maintain clean context. Includes circuit breakers and quality gates."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/auto-sprint"
instructions: "{installed_path}/instructions.xml"
template: false # Action-only orchestrator, no template output

# Sprint tracking
variables:
  sprint_status: "{implementation_artifacts}/sprint-status.yaml"
  project_context: "**/project-context.md"

  # Scope control - determines how many stories to process
  # Modes: "epic" (single epic), "all" (all epics), "count" (next N stories)
  scope_mode: "epic"
  scope_epic_num: "" # Auto-detected from sprint-status if empty; used when scope_mode=epic
  scope_story_limit: 0 # 0 = unlimited within scope; >0 = stop after N stories completed

  # Circuit breakers - prevent runaway execution
  max_iterations: 20 # Absolute cap on loop iterations (create + dev + review each count as 1)
  max_consecutive_failures: 2 # Stop after N consecutive failures (failed dev or failed review)

  # Session log
  session_log: "{implementation_artifacts}/auto-sprint-log-{{date}}.md"

# Sub-workflow references - these are invoked via sub-agents, not directly
sub_workflows:
  create_story:
    command: "{project-root}/.library/commands/bmad/bmad-bmm-create-story.md"
    workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/create-story/workflow.yaml"
  dev_story:
    command: "{project-root}/.library/commands/bmad/bmad-bmm-dev-story.md"
    workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story/workflow.yaml"
  code_review:
    command: "{project-root}/.library/commands/bmad/bmad-bmm-code-review.md"
    workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/code-review/workflow.yaml"
